### ISSUE TITLE
Robocorp portal review

### ISSUE THREAD

**Issue by tonnitommi** [jeev20/MicrosoftTeamsNotifier_Robocorp#1]
Hi!

Thanks for submitting the repo to the Robocorp portal! Looks great, and I was able to test it easily! This is very welcome addition.

Two things I'd ask to change:

- Replace Robocorp Lab mentions with VS Code (Lab is discontinued, development happens now with VS Code and extensions).
- Update the dependencies like this:

```
  - python=3.9.13
  - pip=22.1.2

  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==22.5.2          # https://rpaframework.org/releasenotes.html
    - rpaframework-dialogs==4.0.4   # https://pypi.org/project/rpaframework-dialogs/#history
```

I tested with the above, and all worked well. The reason for adding a separate package for dialogs is that it's deprecated and there is a new assistant implementation. But it still works. :)

**Comment by tonnitommi** [comment]
Ping @jeev20 in case this otherwise goes unnoticed. :)

**Comment by jeev20** [comment]
Hi @tonnitommi 

Will update the repo as requested above.

**Comment by tonnitommi** [comment]
lgtm!
