### ISSUE TITLE
Robocorp portal review / images

### ISSUE THREAD

**Issue by tonnitommi** [jeev20/MicrosoftTeamsNotifier_Robocorp#2]
Hi @jeev20.

One more thing I forgot to check earlier. Could you please change the image URLs to be relative, not absolute? The way they are now means that github blocks them from the external sites like the Portal. Using relative path (like `/images/Success.JPG`) works.

https://github.com/jeev20/MicrosoftTeamsNotifier_Robocorp/blob/750612a9c38e23a034cc1dab4e40af3f6f5038ea/README.md?plain=1#L15

https://github.com/jeev20/MicrosoftTeamsNotifier_Robocorp/blob/750612a9c38e23a034cc1dab4e40af3f6f5038ea/README.md?plain=1#L18

Thanks!

**Comment by jeev20** [comment]
Learnt something new. I did not know github takes relative path. Thanks!
